Add keys for direct room switching
mirukana/mirage pull request #209
Opened 2021-04-09 04:35 UTC by MRAAGH

The one thing better than history navigation keys are keys for jumping directly to your favorite rooms, bindings that always work regardless of context.

This is a draft, ideally we want to offer more than a fixed number of slots. Personally I use 16 slots on a big account, bound to 2- or 3-key chords.

I wasn't able to figure out how to make one `HShortcut` do all this, so I currently have one for each and they're all just copy pasted.

2021-04-09 06:42 UTC, mirukana commented
For the settings.py, you can add  a section in `Keys.Rooms` similar to [`Keys.Rooms.AtIndex`](https://github.com/mirukana/mirage/blob/73af2d80176fa489277920c3eb78bd6d9c8f0f8e/src/config/settings.py#L363), which  accepts any number of user-defined properties. The property values will be a list of keybinds, and the property names can be (make sure to have a comment explaining this):
- An account ID and room ID separated by a space ([example](https://github.com/mirukana/mirage/blob/73af2d80176fa489277920c3eb78bd6d9c8f0f8e/src/config/settings.py#L176))
- Just a room ID, as conveniance for those who have a room not shared between multiple accounts ─ go to that room in the first account that has it 

For the QML code, have a look at how handle any amount of binds for `AtIndex` sections [here](https://github.com/mirukana/mirage/blob/73af2d80176fa489277920c3eb78bd6d9c8f0f8e/src/gui/MainPane/RoomList.qml#L267) (make sure to rebase on latest dev).

2021-04-12 15:55 UTC, MRAAGH commented
I noticed that if I save the configuration file **while Mirage is running**, my bindings stop working.

### Steps to reproduce:

1. Have this configuration:
```
        class Direct:
            "!uxYVyZEASzrDCXMnNO:matrix.org" = ["Ctrl+G,Ctrl+M"]
```
2. Start Mirage
3. Notice that `Ctrl+G,Ctrl+M` works
4. Save the configuration file without changing it
5. Notice that `Ctrl+G,Ctrl+M` does not work any more. `onActivated` does not get called at all.
6. Restart Mirage
7. Notice that `Ctrl+G,Ctrl+M` works again

I also noticed that if I add a new binding with a previously unassigned key, it does work, but only until the next time I save the configuration. I think the entries are being duplicated (added again each time I save the config file)

2021-04-13 03:35 UTC, mirukana requested changes

2021-04-13 03:35 UTC, mirukana commented on src/gui/MainPane/RoomList.qml
> +            const roomIndex = indexOfRoomId(roomId)
You can use `roomList.model.findIndex(roomId)`, no need to make a new function ([code for ModelStore and the model it contains](https://github.com/mirukana/mirage/blob/b62d98ea022e56226f3224acce21f086bfa4709c/src/gui/ModelStore.qml))

2021-04-13 03:35 UTC, mirukana commented on src/config/settings.py
> +            "!uxYVyZEASzrDCXMnNO:matrix.org" = []
The default code shouldn't point to a real room but be a clear example, e;g. `!roomID:example.org`

2021-04-13 03:35 UTC, mirukana commented on src/gui/MainPane/RoomList.qml
> +        const spaceIndex = description.indexOf(" ")
You can do `const [roomId, accountId] = description.split(" ").reverse()`, that's more explicit and gives you `accountId` and `roomId` variables directly

2021-04-15 21:07 UTC, mirukana commented
Fixed the reload problem in d53978f62bab35cdc7e115c50f0571f736814582, rebase the branch on top of it

2021-04-15 21:28 UTC, MRAAGH commented
Great work Miruka, everything works now!

Ready to merge unless you have comments about code style. Oh, is there an "official" name for the form `"@account_2:example.org !room:example.org"` or is it ok to call it `description`?

2021-04-15 21:40 UTC, mirukana commented
I made some changes so that we don't have to wonder about that, see the commit above's bodies. For the code style, note that we use `} else {` on the same line as the if's closing paren, if we can't avoid using elses at all. It should be ready now, thanks for your work!

2021-04-15 21:47 UTC, merged